#!/usr/bin/env php
<?php
require __DIR__."/Application.php";
$name = $argv[1];
$className = "Bot\\Tasks\\${name}";
if (class_exists($className)) {
        $Task = new $className($api,  $services, $mysqli);
        $Task->RUN();
} else {
        echo "Class $className does not exist.";
}
