#!/usr/bin/env php
<?php
$name = $argv[1];
$className = "Bot\\Tasks\\${name}";
if (class_exists($className)) {
        require __DIR__."/ApplicationLocal.php";
        $Task = new $className($api,  $services, $mysqli);
        $Task->RUN();
} else {
        echo "Class $className does not exist.";
}
